### ISSUE TITLE
Is it possible to support networking ?

### ISSUE THREAD

**Issue by tigran-bayburtsyan** [pczarn/rustboot#15]
Hi I'm glad to see this kind of grate repository.

I'm working on low level network programming project, and now I'm looking some good solution to create networking OS based on my network protocol implementation https://github.com/flaxtonio/fntp-c

Do you planning to support some basic networking ?
Or API for driver development ?

**Comment by pczarn** [comment]
:smiley:  Perhaps later this year.

Some folks are far ahead of my repository. Take a look at https://github.com/RustOS-Fork-Holding-Ground/rust-net.

**Comment by tigran-bayburtsyan** [comment]
Ok Thanks :)
